# Generated by Django 5.2.17 on 2026-08-11 02:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyntheticSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_synthetic", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("is_synthetic", True)),
                        name="core_synthetic_session_only",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("activity_key", models.CharField(max_length=64)),
                ("content_version", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("locked", "Locked")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "synthetic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.syntheticsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("base_revision", models.PositiveIntegerField()),
                ("acknowledged_revision", models.PositiveIntegerField()),
                ("acknowledged_at", models.DateTimeField()),
                (
                    "value",
                    models.CharField(
                        choices=[("alpha", "Token A"), ("beta", "Token B"), ("gamma", "Token C")],
                        max_length=16,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="core.activityattempt",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "operation_id"), name="core_unique_synthetic_operation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyntheticResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item_key", models.CharField(default="synthetic-item-1", max_length=64)),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        choices=[("alpha", "Token A"), ("beta", "Token B"), ("gamma", "Token C")],
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="core.activityattempt",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("item_key__startswith", "synthetic-")),
                        name="core_synthetic_item_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__in", ("", "alpha", "beta", "gamma"))),
                        name="core_synthetic_response_value",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="activityattempt",
            constraint=models.UniqueConstraint(
                fields=("synthetic_session", "activity_key"),
                name="core_one_synthetic_attempt_per_activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("activity_key__startswith", "synthetic-")),
                name="core_synthetic_activity_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_version__startswith", "synthetic-")),
                name="core_synthetic_content_version",
            ),
        ),
    ]
